name: my_flutter_repo
description: "My new Flutter project."
publish_to: 'none'
version: 1.0.2

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  material_symbols_icons: ^4.2789.0
  http_parser: ^4.0.2
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  package_info_plus: ^8.1.0
  permission_handler: ^11.3.1
  json_annotation: ^4.9.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  convert: ^3.1.2
  device_info_plus: ^11.1.0
  uuid: ^4.5.1
  fluro: ^2.0.5
  local_auth: ^2.3.0
  local_auth_android: ^1.0.0
  local_auth_darwin: ^1.4.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.0
  path_provider: ^2.1.4
  toastification: ^2.3.0
  fluwx: ^5.1.0
  mobile_scanner: ^6.0.2
  url_launcher: ^6.3.1
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: false
  assets:
    - assets/images/
  fonts:
    - family: IconFont
      fonts:
        - asset: fonts/iconfont.ttf
